package vip.ddm.ddm.dao;

import vip.ddm.ddm.model.CouponStore;

public interface CouponStoreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_store
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_store
     *
     * @mbg.generated
     */
    int insert(CouponStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_store
     *
     * @mbg.generated
     */
    int insertSelective(CouponStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_store
     *
     * @mbg.generated
     */
    CouponStore selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_store
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CouponStore record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_store
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CouponStore record);
}