package vip.ddm.ddm.dao;

import vip.ddm.ddm.model.CouponGoodsGroup;

public interface CouponGoodsGroupMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_goods_group
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_goods_group
     *
     * @mbg.generated
     */
    int insert(CouponGoodsGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_goods_group
     *
     * @mbg.generated
     */
    int insertSelective(CouponGoodsGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_goods_group
     *
     * @mbg.generated
     */
    CouponGoodsGroup selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_goods_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CouponGoodsGroup record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_goods_group
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CouponGoodsGroup record);
}