package vip.ddm.ddm.dao;

import org.springframework.data.repository.query.Param;
import vip.ddm.ddm.model.FullDown;

import java.util.List;

public interface FullDownMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table full_down
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table full_down
     *
     * @mbg.generated
     */
    int insert(FullDown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table full_down
     *
     * @mbg.generated
     */
    int insertSelective(FullDown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table full_down
     *
     * @mbg.generated
     */
    FullDown selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table full_down
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(FullDown record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table full_down
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(FullDown record);

    List<FullDown> findList(@Param("fullDown") FullDown fullDown);
}