package vip.ddm.ddm.dao;

import org.apache.ibatis.annotations.Select;
import org.springframework.data.repository.query.Param;
import vip.ddm.ddm.model.Goods;
import vip.ddm.ddm.vo.GoodsVo;

import java.util.List;

public interface GoodsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    int insert(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    int insertSelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    Goods selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Goods record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Goods record);

    List<GoodsVo> findByParam(@Param(value = "goods") Goods goods,@Param("storeId")Integer storeId);

    @Select("select * from goods where group_id = #{groupId} and status != 0")
    List<Goods> findByGroupId(@Param(value = "groupId") Integer groupId);
}