package vip.ddm.ddm.dao;

import vip.ddm.ddm.model.UserCoupon;

public interface UserCouponMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated
     */
    int insert(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated
     */
    int insertSelective(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated
     */
    UserCoupon selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(UserCoupon record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_coupon
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(UserCoupon record);
}