package vip.ddm.ddm.model;

import java.io.Serializable;

public class CouponGoodsGroup implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_goods_group.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_goods_group.coupon_id
     *
     * @mbg.generated
     */
    private Integer couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column coupon_goods_group.goods_group_id
     *
     * @mbg.generated
     */
    private Integer goodsGroupId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table coupon_goods_group
     *
     * @mbg.generated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_goods_group.id
     *
     * @return the value of coupon_goods_group.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_goods_group.id
     *
     * @param id the value for coupon_goods_group.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_goods_group.coupon_id
     *
     * @return the value of coupon_goods_group.coupon_id
     *
     * @mbg.generated
     */
    public Integer getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_goods_group.coupon_id
     *
     * @param couponId the value for coupon_goods_group.coupon_id
     *
     * @mbg.generated
     */
    public void setCouponId(Integer couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column coupon_goods_group.goods_group_id
     *
     * @return the value of coupon_goods_group.goods_group_id
     *
     * @mbg.generated
     */
    public Integer getGoodsGroupId() {
        return goodsGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column coupon_goods_group.goods_group_id
     *
     * @param goodsGroupId the value for coupon_goods_group.goods_group_id
     *
     * @mbg.generated
     */
    public void setGoodsGroupId(Integer goodsGroupId) {
        this.goodsGroupId = goodsGroupId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table coupon_goods_group
     *
     * @mbg.generated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", couponId=").append(couponId);
        sb.append(", goodsGroupId=").append(goodsGroupId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}